-- Catalogo inicial de exercicios, para o personal nao comecar do zero.
insert into exercicios (nome, grupo_muscular) values
  ('Supino reto com barra',        'Peito'),
  ('Supino inclinado com halter',  'Peito'),
  ('Crucifixo na maquina',         'Peito'),
  ('Crossover na polia',           'Peito'),
  ('Puxada frontal',               'Costas'),
  ('Remada curvada',               'Costas'),
  ('Remada baixa',                 'Costas'),
  ('Barra fixa',                   'Costas'),
  ('Desenvolvimento com halter',   'Ombro'),
  ('Elevacao lateral',             'Ombro'),
  ('Elevacao frontal',             'Ombro'),
  ('Encolhimento',                 'Ombro'),
  ('Rosca direta',                 'Biceps'),
  ('Rosca alternada',              'Biceps'),
  ('Rosca martelo',                'Biceps'),
  ('Triceps na polia',             'Triceps'),
  ('Triceps testa',                'Triceps'),
  ('Mergulho no banco',            'Triceps'),
  ('Agachamento livre',            'Perna'),
  ('Leg press',                    'Perna'),
  ('Cadeira extensora',            'Perna'),
  ('Mesa flexora',                 'Perna'),
  ('Stiff',                        'Perna'),
  ('Afundo',                       'Perna'),
  ('Panturrilha em pe',            'Perna'),
  ('Elevacao pelvica',             'Gluteo'),
  ('Cadeira abdutora',             'Gluteo'),
  ('Coice na polia',               'Gluteo'),
  ('Abdominal supra',              'Core'),
  ('Prancha',                      'Core'),
  ('Esteira',                      'Cardio'),
  ('Bicicleta ergometrica',        'Cardio')
on conflict (nome) do nothing;
